export { faHome } from "@fortawesome/pro-regular-svg-icons/faHome"
export { faMapMarkerAlt } from "@fortawesome/pro-regular-svg-icons/faMapMarkerAlt"
export { faBookmark } from "@fortawesome/pro-regular-svg-icons/faBookmark"
export { faBookmark as fasBookmark } from "@fortawesome/pro-solid-svg-icons/faBookmark"
export { faMap } from "@fortawesome/pro-regular-svg-icons/faMap"
export { faSearch } from "@fortawesome/pro-regular-svg-icons/faSearch"
export { faEllipsisV } from "@fortawesome/pro-regular-svg-icons/faEllipsisV"
export { faInfoCircle } from "@fortawesome/pro-regular-svg-icons/faInfoCircle"
export { faChevronRight } from "@fortawesome/pro-regular-svg-icons/faChevronRight"
export { faArrowLeft } from "@fortawesome/pro-regular-svg-icons/faArrowLeft"
export { faBus } from "@fortawesome/pro-regular-svg-icons/faBus"
export { faPlusCircle } from "@fortawesome/pro-regular-svg-icons/faPlusCircle"
export { faMapMarkerPlus } from "@fortawesome/pro-regular-svg-icons/faMapMarkerPlus"
export { faMapMarkedAlt } from "@fortawesome/pro-regular-svg-icons/faMapMarkedAlt"
export { faCheck } from "@fortawesome/pro-regular-svg-icons/faCheck"
export { faTrashAlt } from "@fortawesome/pro-regular-svg-icons/faTrashAlt"
